### ISSUE TITLE
Minimum List::Util version

### ISSUE THREAD

**Issue by eserte** [GrantStreetGroup/DBIx-OnlineDDL#1]
It seems that a minimum List::Util version has to be specified, otherwise the test suite may fail. Example:
http://www.cpantesters.org/cpan/report/00d4ee86-d122-11e8-98d5-bb14e5798fec
According to https://metacpan.org/changes/release/PEVANS/Scalar-List-Utils-1.50#L58 uniq() was added in 1.44.

**Comment by SineSwiper** [comment]
Thanks.  I accounted for any/all, and Sub::Name, but I forgot about `uniq`.
